In [1]:
from pathlib import Path
import json
import time
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch

PROJECT_ROOT = Path.cwd().parent

PROCESSED_DATA = (
    PROJECT_ROOT
    / "datasets"
    / "processed"
)

MODELS_DIR = (
    PROJECT_ROOT
    / "models"
)

EXPERIMENTS_DIR = (
    PROJECT_ROOT
    / "experiments"
)

MODELS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

EXPERIMENTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

DEVICE = 0 if torch.cuda.is_available() else "cpu"

print("Inspectra — Baseline Training")
print("=" * 60)
print(
    "PyTorch:",
    torch.__version__
)
print(
    "CUDA:",
    torch.cuda.is_available()
)

if torch.cuda.is_available():
    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )

print(
    "Device:",
    DEVICE
)

Inspectra — Baseline Training
============================================================
PyTorch: 2.5.1+cu121
CUDA: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Device: 0

In [2]:
DATASET_TASKS = {
    "bottle": "detection",
    "pcb": "detection",
    "textile": "detection",
    "welding": "detection",
    "road": "classification",
    "steel": "segmentation",
}


def count_images(path):

    extensions = {
        ".jpg",
        ".jpeg",
        ".png",
        ".bmp",
        ".tif",
        ".tiff",
        ".webp",
    }

    if not path.exists():
        return 0

    return sum(
        1
        for file in path.rglob("*")
        if (
            file.is_file()
            and file.suffix.lower()
            in extensions
        )
    )


readiness = []

for dataset, task in DATASET_TASKS.items():

    root = (
        PROCESSED_DATA
        / dataset
    )

    train_count = count_images(
        root / "train"
    )

    val_count = count_images(
        root / "val"
    )

    test_count = count_images(
        root / "test"
    )

    ready = (
        train_count > 0
        and val_count > 0
        and test_count > 0
    )

    readiness.append(
        {
            "dataset": dataset,
            "task": task,
            "train": train_count,
            "val": val_count,
            "test": test_count,
            "ready": ready,
        }
    )


readiness_df = pd.DataFrame(
    readiness
)

display(
    readiness_df
)

   dataset            task  train   val  test  ready
0   bottle       detection   5420  1799   920   True
1      pcb       detection   8534  1066  1068   True
2  textile       detection      0     0     0  False
3  welding       detection      0     0     0  False
4     road  classification  28000  6000  6000   True
5    steel    segmentation      0     0     0  False

In [3]:
DETECTION_DATASETS = {
    "bottle": {
        "classes": [
            "Cap",
            "Missing",
            "Wrong bottle",
            "box",
        ],
        "model": "yolov8n.pt",
        "epochs": 50,
        "batch": 4,
        "imgsz": 640,
    },

    "pcb": {
        "classes": [
            "mouse_bite",
            "spur",
            "missing_hole",
            "short",
            "open_circuit",
            "spurious_copper",
        ],
        "model": "yolov8n.pt",
        "epochs": 50,
        "batch": 4,
        "imgsz": 640,
    },

    "textile": {
        "classes": [],
        "model": "yolov8n.pt",
        "epochs": 50,
        "batch": 4,
        "imgsz": 640,
    },

    "welding": {
        "classes": [
            "adj",
            "int",
            "geo",
            "pro",
            "non",
        ],
        "model": "yolov8n.pt",
        "epochs": 50,
        "batch": 4,
        "imgsz": 640,
    },
}

In [4]:
import yaml


def create_yolo_yaml(
    dataset_name,
    classes
):

    root = (
        PROCESSED_DATA
        / dataset_name
    )

    config = {
        "path": str(root.resolve()),
        "train": "train/images",
        "val": "val/images",
        "test": "test/images",
        "nc": len(classes),
        "names": classes,
    }

    yaml_path = (
        root
        / "data.yaml"
    )

    with open(
        yaml_path,
        "w",
        encoding="utf-8"
    ) as file:

        yaml.safe_dump(
            config,
            file,
            sort_keys=False
        )

    return yaml_path

In [5]:
for dataset, config in DETECTION_DATASETS.items():

    if not config["classes"]:
        continue

    if not (
        PROCESSED_DATA
        / dataset
        / "train"
        / "images"
    ).exists():
        continue

    yaml_path = create_yolo_yaml(
        dataset,
        config["classes"]
    )

    print(
        f"{dataset:10} -> {yaml_path}"
    )

bottle     -> d:\Inspectra\datasets\processed\bottle\data.yaml
pcb        -> d:\Inspectra\datasets\processed\pcb\data.yaml
welding    -> d:\Inspectra\datasets\processed\welding\data.yaml

In [6]:
from ultralytics import YOLO


def train_detection_baseline(
    dataset_name,
    config
):

    dataset_root = (
        PROCESSED_DATA
        / dataset_name
    )

    train_dir = (
        dataset_root
        / "train"
        / "images"
    )

    val_dir = (
        dataset_root
        / "val"
        / "images"
    )

    if not train_dir.exists():
        print(
            f"{dataset_name}: training data missing"
        )
        return None

    if count_images(train_dir) == 0:
        print(
            f"{dataset_name}: no training images"
        )
        return None

    if count_images(val_dir) == 0:
        print(
            f"{dataset_name}: no validation images"
        )
        return None

    yaml_path = create_yolo_yaml(
        dataset_name,
        config["classes"]
    )

    output_dir = (
        EXPERIMENTS_DIR
        / dataset_name
        / "baseline"
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    model = YOLO(
        config["model"]
    )

    start_time = time.time()

    results = model.train(
        data=str(yaml_path),
        epochs=config["epochs"],
        batch=config["batch"],
        imgsz=config["imgsz"],
        device=DEVICE,
        project=str(
            output_dir
        ),
        name="baseline",
        pretrained=True,
        workers=4,
        seed=42,
        deterministic=True,
        plots=True,
        save=True,
        verbose=True,
    )

    elapsed = (
        time.time()
        - start_time
    )

    print(
        f"\n{dataset_name.upper()}"
    )

    print(
        f"Training time: "
        f"{elapsed / 60:.2f} minutes"
    )

    print(
        "Best model:",
        output_dir
        / "baseline"
        / "weights"
        / "best.pt"
    )

    return results

In [7]:
bottle_result = train_detection_baseline(
    "bottle",
    DETECTION_DATASETS["bottle"]
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 1.5MB/s 4.2s.1s<0.1s4.5s7s
Ultralytics 8.4.117  Python-3.11.5 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 6GB Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=d:\Inspectra\datasets\processed\bottle\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=d:\Inspectra\experiments\bottle\baseline, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=D:\Inspectra\experiments\bottle\baseline\baseline, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752092  ultralytics.nn.modules.head.Detect           [4, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,011,628 parameters, 3,011,612 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 6.7MB/s 0.8s.7s<0.1s.5s3s

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

AMP: checks passed
WARNING train: Slow image access detected (ping: 0.20.1 ms, read: 1.80.2 MB/s, size: 34.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning D:\Inspectra\datasets\processed\bottle\train\labels... 5420 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5420/5420 402.5it/s 13.5s0.1s
train: New cache created: D:\Inspectra\datasets\processed\bottle\train\labels.cache
WARNING val: Slow image access detected (ping: 0.20.1 ms, read: 3.60.7 MB/s, size: 41.5 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning D:\Inspectra\datasets\processed\bottle\val\labels... 1799 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1799/1799 396.0it/s 4.5s0.1s
val: New cache created: D:\Inspectra\datasets\processed\bottle\val\labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.00125, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to D:\Inspectra\experiments\bottle\baseline\baseline\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to D:\Inspectra\experiments\bottle\baseline\baseline
Starting training for 50 epochs...

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50     0.592G     0.7514      1.832      1.108         18        640: 100% ━━━━━━━━━━━━ 1355/1355 13.8it/s 1:380.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 15.7it/s 14.3s0.1s
                   all       1799       3479      0.821      0.775      0.814      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50     0.688G     0.6246      1.469      1.165         10        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:24

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       2/50     0.688G     0.6895      1.109      1.059         13        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.4it/s 13.8s0.1s
                   all       1799       3479      0.942      0.837      0.916      0.764

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50     0.688G     0.7235     0.9641      1.049         10        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:26

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       3/50     0.688G     0.6651     0.9308      1.045         17        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.5it/s 13.6s0.1s
                   all       1799       3479       0.93      0.874      0.944      0.785

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50     0.688G     0.6371     0.7169       1.05         20        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       4/50     0.688G     0.6396     0.8428      1.027         22        640: 100% ━━━━━━━━━━━━ 1355/1355 15.6it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.1it/s 14.0s0.1s
                   all       1799       3479      0.958      0.886      0.951      0.804

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50     0.688G     0.6629     0.6921      1.036         13        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:43

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       5/50     0.688G     0.6096     0.7592      1.012         12        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.5it/s 13.6s0.1s
                   all       1799       3479      0.907      0.888      0.946        0.8

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50     0.688G     0.4978     0.5946     0.9321         11        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:41

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       6/50     0.688G     0.5829     0.7095     0.9937         14        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.6s0.1s
                   all       1799       3479       0.93      0.937      0.964      0.828

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50     0.688G     0.4706     0.7788     0.9103         13        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:03

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       7/50     0.688G      0.565     0.6772     0.9825         11        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.7it/s 13.5s0.1s
                   all       1799       3479      0.926      0.949      0.971       0.85

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50     0.688G     0.4133     0.5104     0.9025         15        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:55

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       8/50     0.688G     0.5448      0.635      0.974         15        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.2s0.1s
                   all       1799       3479      0.944      0.925      0.967      0.841

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50     0.688G      0.491       0.44     0.9042         11        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:17

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       9/50     0.688G     0.5399     0.6165      0.975         15        640: 100% ━━━━━━━━━━━━ 1355/1355 16.1it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.1it/s 13.2s0.1s
                   all       1799       3479      0.925       0.96      0.971      0.844

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50     0.688G     0.4597     0.5286     0.9716         18        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:21

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      10/50     0.688G     0.5289      0.594     0.9683         18        640: 100% ━━━━━━━━━━━━ 1355/1355 16.1it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.1it/s 13.2s0.1s
                   all       1799       3479      0.932      0.965      0.974      0.863

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50     0.688G      0.519     0.5229     0.9249         18        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:34

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      11/50     0.688G     0.5122     0.5714     0.9569         21        640: 100% ━━━━━━━━━━━━ 1355/1355 16.1it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.2s0.1s
                   all       1799       3479      0.945      0.947      0.974      0.863

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50     0.688G     0.4484     0.4777     0.9082         14        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:23

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      12/50     0.688G     0.5163     0.5611     0.9606         16        640: 100% ━━━━━━━━━━━━ 1355/1355 16.2it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.2s0.1s
                   all       1799       3479      0.953      0.945      0.975      0.867

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50     0.688G     0.4849     0.4734       1.04         18        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:12

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      13/50     0.688G     0.4916      0.545     0.9475         17        640: 100% ━━━━━━━━━━━━ 1355/1355 16.1it/s 1:240.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.3s0.1s
                   all       1799       3479      0.958      0.941      0.974      0.861

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50     0.688G     0.4353     0.4334     0.8848         15        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:19

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      14/50     0.688G     0.4977     0.5362     0.9529         15        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 15.8it/s 14.3s0.1s
                   all       1799       3479      0.949      0.955      0.975      0.864

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50     0.688G     0.4653     0.5659     0.9276         16        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:57

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      15/50     0.688G     0.4823     0.5177      0.948         20        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.6s0.1s
                   all       1799       3479      0.947      0.965      0.979      0.871

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50     0.688G     0.4711     0.4521     0.9217         17        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:19

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      16/50     0.688G     0.4769      0.512     0.9413         11        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479      0.956      0.949      0.978      0.876

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50     0.688G     0.4333     0.3954     0.9329         14        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      17/50     0.688G     0.4712      0.502     0.9398         17        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.2it/s 13.9s0.1s
                   all       1799       3479      0.943      0.955      0.971      0.868

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50     0.688G     0.4131     0.3989     0.9019         18        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:12

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      18/50     0.688G     0.4639     0.4889      0.937         23        640: 100% ━━━━━━━━━━━━ 1355/1355 15.6it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.1it/s 14.0s0.1s
                   all       1799       3479      0.957      0.948      0.978      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50     0.688G       0.39     0.5321     0.9343         16        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      19/50     0.688G      0.467     0.4906     0.9377         11        640: 100% ━━━━━━━━━━━━ 1355/1355 15.9it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.8it/s 13.4s0.1s
                   all       1799       3479      0.964       0.95      0.976      0.873

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50     0.688G     0.5553     0.4944     0.9497         16        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:57

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      20/50     0.688G     0.4594     0.4763     0.9333         21        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 15.7it/s 14.4s0.1s
                   all       1799       3479      0.953      0.957      0.981      0.878

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50     0.688G     0.4808     0.5835     0.9204         20        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:02

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      21/50     0.688G     0.4475     0.4618     0.9274         14        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.4it/s 13.7s0.1s
                   all       1799       3479      0.962      0.954      0.978      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50     0.688G     0.4234     0.4894      1.007         10        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:26

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      22/50     0.688G     0.4465     0.4658     0.9298         19        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.9it/s 13.3s0.1s
                   all       1799       3479      0.961      0.949      0.978      0.877

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50     0.688G     0.3666     0.4187      0.925         20        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      23/50     0.688G     0.4418     0.4506      0.927         16        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.5it/s 13.7s0.1s
                   all       1799       3479      0.969       0.95      0.978      0.879

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50     0.688G     0.4165      0.462      0.925         11        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:06

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      24/50     0.688G     0.4436     0.4483     0.9275         21        640: 100% ━━━━━━━━━━━━ 1355/1355 16.0it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.2s0.1s
                   all       1799       3479       0.96      0.958      0.981      0.881

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50     0.688G     0.5144     0.4481     0.9318         22        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:19

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      25/50     0.688G     0.4358     0.4388     0.9238         20        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479      0.952      0.966      0.981      0.887

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50     0.688G     0.4443     0.6546      1.023         14        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:15

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      26/50     0.688G     0.4308      0.437     0.9209         17        640: 100% ━━━━━━━━━━━━ 1355/1355 14.8it/s 1:310.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.4it/s 13.7s0.1s
                   all       1799       3479      0.961      0.959      0.978       0.88

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50     0.688G     0.5192     0.4187     0.8852         19        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:54

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      27/50     0.688G     0.4248     0.4262     0.9192         15        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.5it/s 13.7s0.1s
                   all       1799       3479      0.964      0.961      0.981      0.886

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50     0.688G     0.4151     0.5217     0.8739         15        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:30

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      28/50     0.688G     0.4242      0.423     0.9189         14        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.6s0.1s
                   all       1799       3479      0.958      0.963      0.981      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50     0.688G     0.4029     0.3592     0.9134         18        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:29

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      29/50     0.688G     0.4157      0.419     0.9164         18        640: 100% ━━━━━━━━━━━━ 1355/1355 15.6it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.2it/s 13.8s0.1s
                   all       1799       3479      0.961      0.963      0.982      0.891

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50     0.688G     0.3782     0.3198     0.8843         16        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:37

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      30/50     0.688G     0.4123     0.4165     0.9139         17        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.7it/s 13.4s0.1s
                   all       1799       3479      0.964      0.965      0.982       0.89

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50     0.688G     0.4421     0.4426     0.9449         17        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:25

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      31/50     0.688G     0.4088     0.4115     0.9135         11        640: 100% ━━━━━━━━━━━━ 1355/1355 15.2it/s 1:290.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.1it/s 14.0s0.1s
                   all       1799       3479      0.965      0.963      0.982       0.89

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50     0.688G     0.4294     0.4969      0.914          9        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:22

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      32/50     0.688G     0.4053     0.4022      0.912         13        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479      0.971      0.957      0.982      0.889

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/50     0.688G     0.3485     0.4473     0.8926         22        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:19

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      33/50     0.688G     0.4005      0.398     0.9108          9        640: 100% ━━━━━━━━━━━━ 1355/1355 15.4it/s 1:280.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479      0.974      0.955      0.983       0.89

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/50     0.688G     0.3537     0.5606     0.8233         18        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:45

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      34/50     0.688G      0.399     0.3944     0.9101         13        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.7it/s 13.5s0.1s
                   all       1799       3479      0.965      0.966      0.983       0.89

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/50     0.688G     0.4572     0.3832     0.9285         11        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:17

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      35/50     0.688G      0.398     0.3886     0.9105         25        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:280.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.0it/s 14.1s0.1s
                   all       1799       3479      0.966       0.97      0.983      0.892

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      36/50     0.688G     0.5054     0.4581     0.9619         14        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:27

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      36/50     0.688G     0.3886     0.3792     0.9057         10        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:280.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479       0.97      0.965      0.982      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      37/50     0.688G     0.4276     0.4763     0.8818         11        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:29

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      37/50     0.688G      0.386     0.3747     0.9027         14        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.5s0.1s
                   all       1799       3479      0.962      0.969      0.983      0.893

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      38/50     0.688G     0.3812     0.3079     0.9147         10        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:33

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      38/50     0.688G     0.3809      0.369      0.903         16        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.6s0.1s
                   all       1799       3479      0.964      0.972      0.982      0.895

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      39/50     0.688G     0.4493     0.3815     0.9148         12        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:32

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      39/50     0.688G     0.3803     0.3681     0.9044         14        640: 100% ━━━━━━━━━━━━ 1355/1355 12.7it/s 1:470.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 15.9it/s 14.1s0.1s
                   all       1799       3479      0.965      0.968      0.983      0.898

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      40/50     0.688G     0.2743     0.3392     0.9005         24        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:27

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      40/50     0.688G     0.3756     0.3652     0.8978         20        640: 100% ━━━━━━━━━━━━ 1355/1355 15.4it/s 1:280.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.8it/s 13.4s0.1s
                   all       1799       3479      0.963      0.969      0.983      0.897
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      41/50     0.688G     0.7824     0.5697     0.8932          5        640: 0% ──────────── 0/1355  0.2s

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      41/50     0.688G     0.4144     0.2878     0.8844          8        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.2it/s 13.9s0.1s
                   all       1799       3479      0.959      0.973      0.984      0.897

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      42/50     0.688G     0.4026     0.2594     0.8813          8        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:38

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      42/50     0.688G     0.4059     0.2788     0.8809          9        640: 100% ━━━━━━━━━━━━ 1355/1355 15.9it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.4it/s 13.8s0.1s
                   all       1799       3479      0.963      0.972      0.982      0.894

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      43/50     0.688G     0.4078     0.3537      1.124         10        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:29

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      43/50     0.688G     0.4005     0.2689     0.8779         10        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.4it/s 13.8s0.1s
                   all       1799       3479       0.97      0.969      0.983      0.898

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      44/50     0.688G     0.3437     0.2268     0.8389          9        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:23

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      44/50     0.688G     0.3894     0.2602     0.8736          7        640: 100% ━━━━━━━━━━━━ 1355/1355 15.9it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.7it/s 13.4s0.1s
                   all       1799       3479      0.968      0.971      0.984      0.902

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      45/50     0.688G     0.3418     0.2452     0.8599          7        640: 0% ──────────── 1/1355 2.5it/s 0.1s<9:10

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      45/50     0.688G     0.3844     0.2586     0.8722          7        640: 100% ━━━━━━━━━━━━ 1355/1355 15.9it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.9it/s 13.3s0.1s
                   all       1799       3479      0.966      0.969      0.984        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      46/50     0.688G     0.3409     0.2191     0.9141          7        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:41

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      46/50     0.688G     0.3813     0.2536     0.8701          6        640: 100% ━━━━━━━━━━━━ 1355/1355 15.8it/s 1:260.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 15.9it/s 14.2s0.1s
                   all       1799       3479      0.967      0.971      0.984        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      47/50     0.688G     0.3452     0.1745     0.7955          7        640: 0% ──────────── 1/1355 2.2it/s 0.1s<10:06

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      47/50     0.688G     0.3773     0.2452     0.8674          8        640: 100% ━━━━━━━━━━━━ 1355/1355 15.5it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.5s0.1s
                   all       1799       3479      0.969      0.971      0.984      0.902

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      48/50     0.688G     0.6378     0.3081      1.149          6        640: 0% ──────────── 1/1355 2.3it/s 0.1s<9:48

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      48/50     0.688G     0.3705     0.2425     0.8676         11        640: 100% ━━━━━━━━━━━━ 1355/1355 15.6it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.3it/s 13.8s0.1s
                   all       1799       3479      0.972      0.966      0.984      0.901

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      49/50     0.688G     0.3666     0.2509     0.8177          8        640: 0% ──────────── 1/1355 2.1it/s 0.1s<10:30

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      49/50     0.688G     0.3658     0.2372     0.8644          6        640: 100% ━━━━━━━━━━━━ 1355/1355 15.7it/s 1:270.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.1it/s 14.0s0.1s
                   all       1799       3479      0.969       0.97      0.982        0.9

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      50/50     0.688G     0.2605     0.1551     0.8828          6        640: 0% ──────────── 1/1355 2.4it/s 0.1s<9:28

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      50/50     0.688G     0.3647     0.2344     0.8634          9        640: 100% ━━━━━━━━━━━━ 1355/1355 15.9it/s 1:250.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 16.6it/s 13.5s0.1s
                   all       1799       3479      0.969       0.97      0.982      0.901

50 epochs completed in 1.402 hours.
Optimizer stripped from D:\Inspectra\experiments\bottle\baseline\baseline\weights\last.pt, 6.3MB
Optimizer stripped from D:\Inspectra\experiments\bottle\baseline\baseline\weights\best.pt, 6.3MB

Validating D:\Inspectra\experiments\bottle\baseline\baseline\weights\best.pt...
Ultralytics 8.4.117  Python-3.11.5 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 6GB Laptop GPU, 6144MiB)
Model summary (fused): 73 layers, 3,006,428 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 225/225 17.0it/s 13.3s0.1s
                   all       1799       3479      0.968      0.971      0.984      0.901
                   Cap        888        893      0.966      0.968      0.987      0.877
               Missing        673        856      0.998      0.995      0.994      0.862
          Wrong bottle        839        875      0.975      0.969      0.974      0.893
                   box        850        855      0.933       0.95      0.982      0.974
Speed: 0.3ms preprocess, 3.3ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to D:\Inspectra\experiments\bottle\baseline\baseline

BOTTLE
Training time: 85.33 minutes
Best model: d:\Inspectra\experiments\bottle\baseline\baseline\weights\best.pt

In [8]:
pcb_result = train_detection_baseline(
    "pcb",
    DETECTION_DATASETS["pcb"]
)

Ultralytics 8.4.117  Python-3.11.5 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 6GB Laptop GPU, 6144MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=4, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=d:\Inspectra\datasets\processed\pcb\data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=baseline, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=d:\Inspectra\experiments\pcb\baseline, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=D:\Inspectra\experiments\pcb\baseline\baseline, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    752482  ultralytics.nn.modules.head.Detect           [6, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,012,018 parameters, 3,012,002 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

AMP: checks passed
WARNING train: Slow image access detected (ping: 0.30.1 ms, read: 3.71.6 MB/s, size: 94.4 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
train: Scanning D:\Inspectra\datasets\processed\pcb\train\labels... 6370 images, 2164 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 8534/8534 303.8it/s 28.1s0.1ss
train: New cache created: D:\Inspectra\datasets\processed\pcb\train\labels.cache
WARNING val: Slow image access detected (ping: 0.20.1 ms, read: 10.12.0 MB/s, size: 105.8 KB). Use local storage instead of remote/mounted storage for better performance. See https://docs.ultralytics.com/guides/model-training-tips/
val: Scanning D:\Inspectra\datasets\processed\pcb\val\labels... 802 images, 264 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1066/1066 277.5it/s 3.8s0.1s
val: New cache created: D:\Inspectra\datasets\processed\pcb\val\labels.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to D:\Inspectra\experiments\pcb\baseline\baseline\labels.jpg...
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to D:\Inspectra\experiments\pcb\baseline\baseline
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50       0.6G      1.185      20.41     0.9223          3        640: 0% ──────────── 1/2134 1.6it/s 0.2s<22:34

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       1/50     0.633G      2.323      4.967      1.402          4        640: 100% ━━━━━━━━━━━━ 2134/2134 15.5it/s 2:180.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.1it/s 7.8s0.1s
                   all       1066       1595      0.571      0.616      0.578      0.252

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50     0.729G      2.114      3.076      1.383          9        640: 0% ──────────── 1/2134 2.2it/s 0.1s<16:00

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       2/50     0.729G      2.004      2.387      1.257          1        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.6it/s 7.6s0.1s
                   all       1066       1595      0.634      0.777      0.726      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50     0.729G      1.771      1.596      1.153          8        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:36

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       3/50     0.729G      1.936      1.802       1.23          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:140.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.4it/s 7.7s0.1s
                   all       1066       1595      0.708      0.792      0.794      0.365

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50     0.729G      2.095       1.93      1.227         19        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:31

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       4/50     0.729G      1.903      1.632      1.219          1        640: 100% ━━━━━━━━━━━━ 2134/2134 15.7it/s 2:160.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 16.4it/s 8.2s0.1s
                   all       1066       1595      0.773      0.806      0.858      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50     0.729G      1.897      1.793      1.288          7        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:27

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       5/50     0.729G      1.872        1.5        1.2          4        640: 100% ━━━━━━━━━━━━ 2134/2134 15.9it/s 2:150.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.1it/s 7.8s0.1s
                   all       1066       1595      0.783      0.841      0.874      0.421

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50     0.729G      1.709      1.429       1.21          8        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:45

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       6/50     0.729G      1.827      1.364      1.173          5        640: 100% ━━━━━━━━━━━━ 2134/2134 15.6it/s 2:170.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.3it/s 7.8s0.1s
                   all       1066       1595      0.844      0.845      0.903      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50     0.729G      1.946      1.289      1.255          6        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:41

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       7/50     0.729G      1.815      1.328      1.166          8        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:140.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.7it/s 7.6s0.1s
                   all       1066       1595      0.917      0.888      0.936      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50     0.729G      1.816      1.162      1.096         20        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       8/50     0.729G      1.788      1.247      1.155          1        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.7it/s 7.6s0.1s
                   all       1066       1595      0.903      0.877      0.936      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50     0.729G      1.683      1.696      1.259          2        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:50

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

       9/50     0.729G      1.775      1.256      1.154          4        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.884      0.864      0.922      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50     0.729G      1.652      1.078      1.136         14        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:11

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      10/50     0.729G      1.777      1.202       1.15          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.906      0.879      0.939      0.473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50     0.729G      1.805      5.489     0.9889          1        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:56

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      11/50      0.73G      1.753      1.178      1.141          9        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.7it/s 7.6s0.1s
                   all       1066       1595      0.938      0.922      0.954      0.486

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50      0.73G      1.924      1.082      1.208         11        640: 0% ──────────── 1/2134 2.2it/s 0.1s<16:22

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      12/50      0.73G      1.746       1.12      1.131          6        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.6it/s 7.6s0.1s
                   all       1066       1595      0.944      0.928      0.962      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50      0.73G      1.678      1.222      1.063          8        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:42

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      13/50      0.73G      1.715      1.096      1.123          0        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.961      0.947      0.967      0.491

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50      0.73G      1.628      1.146      1.031          8        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:28

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      14/50      0.73G      1.724      1.058      1.128          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595      0.943      0.939      0.965       0.49

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50      0.73G       1.41     0.8961      1.117          2        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:38

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      15/50      0.73G      1.713      1.061       1.12          5        640: 100% ━━━━━━━━━━━━ 2134/2134 15.9it/s 2:140.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.2it/s 7.8s0.1s
                   all       1066       1595       0.96      0.944      0.969      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50      0.73G      1.692     0.9194      1.056         13        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:49

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      16/50      0.73G      1.708      1.015      1.119         15        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.966      0.951      0.972      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50      0.73G      1.423     0.8851      1.031         11        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:13

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      17/50      0.73G       1.69      1.005      1.108          7        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.6it/s 7.6s0.1s
                   all       1066       1595      0.958      0.946      0.975      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50      0.73G      2.156     0.8933      1.276          7        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:18

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      18/50      0.73G      1.687     0.9791      1.107          7        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.967      0.946      0.971      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50      0.73G      1.957      1.142      1.288         14        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:56

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      19/50      0.73G       1.67     0.9787      1.094          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.5s0.1s
                   all       1066       1595      0.955      0.944      0.972      0.508

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50      0.73G      1.555     0.9333      1.176         10        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:21

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      20/50      0.73G       1.67     0.9421      1.099          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.961       0.96      0.976      0.513

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50      0.73G      1.414     0.9553      1.058          6        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:09

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      21/50      0.73G      1.658     0.9517      1.097          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.971      0.963      0.976      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50      0.73G      1.437      0.812      1.128          7        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:13

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      22/50      0.73G      1.649     0.9438      1.097          0        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.971      0.955      0.976      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50      0.73G      1.635     0.8549      1.231          7        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:14

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      23/50      0.73G      1.669     0.9179      1.101          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595      0.976      0.964      0.979      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50      0.73G      1.618     0.7537      1.091         13        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:38

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      24/50      0.73G      1.656      0.897      1.098          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.968       0.96       0.98      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50      0.73G      2.258      1.253      1.228          6        640: 0% ──────────── 1/2134 2.6it/s 0.1s<13:44

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      25/50      0.73G      1.641     0.8992      1.091          6        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.969      0.959      0.979      0.521

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50      0.73G      1.875     0.7961      1.087         13        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:29

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      26/50      0.73G      1.636     0.8844      1.088          1        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.5s0.1s
                   all       1066       1595      0.969      0.973      0.981      0.526

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50      0.73G       2.52      3.035      1.467          1        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:49

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      27/50      0.73G       1.64      0.881      1.088          8        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.975      0.972       0.98      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50      0.73G      1.642     0.9045      1.049          5        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:13

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      28/50      0.73G      1.622     0.8643      1.086          2        640: 100% ━━━━━━━━━━━━ 2134/2134 15.8it/s 2:150.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 16.7it/s 8.0s0.1s
                   all       1066       1595      0.973      0.964       0.98      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50      0.73G      1.824     0.6873      1.106          6        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:36

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      29/50      0.73G       1.63     0.8548      1.089          6        640: 100% ━━━━━━━━━━━━ 2134/2134 14.4it/s 2:290.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595       0.98      0.964      0.982       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50      0.73G      1.884      1.433     0.9685          2        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:30

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      30/50      0.73G      1.618     0.8426      1.074          3        640: 100% ━━━━━━━━━━━━ 2134/2134 15.9it/s 2:140.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.976      0.967      0.983      0.531

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50      0.73G      1.898      1.072       1.21         12        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:20

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      31/50      0.73G      1.608     0.8274      1.076          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.0it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.978      0.969      0.981      0.533

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50      0.73G      1.937      3.179      1.262          1        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:26

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      32/50      0.73G        1.6     0.8312      1.079          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.973      0.973      0.981      0.538

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/50      0.73G      1.546     0.8401     0.9505         12        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:54

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      33/50      0.73G      1.604      0.808      1.079          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.5s0.1s
                   all       1066       1595      0.979      0.966      0.983      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/50      0.73G      1.993     0.9928      1.295          6        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:49

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      34/50      0.73G      1.588      0.805      1.069          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.974      0.974      0.982      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/50      0.73G      1.291     0.5945      1.033          2        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:46

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      35/50      0.73G      1.584     0.7848      1.071          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:130.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.977      0.969      0.983      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      36/50      0.73G      1.752     0.9077      1.089         10        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:50

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      36/50      0.73G      1.565     0.8053      1.061          4        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.978      0.973      0.984      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      37/50      0.73G      1.696     0.7913      1.071         10        640: 0% ──────────── 1/2134 2.4it/s 0.1s<15:04

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      37/50      0.73G      1.569     0.7687      1.063          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595      0.979      0.973      0.981       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      38/50      0.73G      1.678     0.6984       1.11         15        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:28

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      38/50      0.73G      1.555     0.7659      1.062          4        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.979      0.967      0.983      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      39/50      0.73G      1.562     0.6879      1.067          6        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:09

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      39/50      0.73G      1.551     0.7686      1.052          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.5s0.1s
                   all       1066       1595      0.977      0.972      0.982       0.54

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      40/50      0.73G      1.226     0.6428     0.9874          4        640: 0% ──────────── 1/2134 2.5it/s 0.1s<14:26

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      40/50      0.73G      1.542     0.7562      1.059          8        640: 100% ━━━━━━━━━━━━ 2134/2134 16.1it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595      0.977      0.974      0.984      0.545
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      41/50      0.73G      1.526     0.7873      1.084          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.9it/s 7.5s0.1s
                   all       1066       1595      0.978      0.966      0.984      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      42/50      0.73G       1.43     0.5902     0.9692          2        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:49

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      42/50      0.73G      1.523     0.7525       1.08          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:110.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.8it/s 7.5s0.1s
                   all       1066       1595      0.975      0.972      0.984      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      43/50      0.73G      1.526     0.6399      1.104          5        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:37

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      43/50      0.73G      1.512     0.7779      1.074          5        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 17.7it/s 7.6s0.1s
                   all       1066       1595      0.978      0.971      0.982      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      44/50      0.73G      1.582      0.688      1.184          4        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:56

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      44/50      0.73G      1.508     0.7408      1.073          2        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.4s0.1s
                   all       1066       1595      0.978      0.971      0.985      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      45/50      0.73G      1.601      1.966      1.188          1        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:34

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      45/50      0.73G      1.498     0.7687      1.073          1        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:110.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.2it/s 7.4s0.1s
                   all       1066       1595      0.976      0.976      0.983      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      46/50      0.73G      1.527     0.6534       1.21          6        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:36

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      46/50      0.73G      1.495     0.7001      1.076          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.976      0.976      0.986      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      47/50      0.73G      1.498     0.6668      0.905          9        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:56

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      47/50      0.73G      1.484     0.7322      1.065          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.971       0.98      0.987      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      48/50      0.73G      1.268     0.6354     0.9234          8        640: 0% ──────────── 1/2134 2.3it/s 0.1s<15:09

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      48/50      0.73G      1.488     0.7041      1.065          4        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.0it/s 7.5s0.1s
                   all       1066       1595      0.973      0.979      0.985      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      49/50      0.73G      1.388     0.5552      1.008          5        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:54

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      49/50      0.73G      1.472     0.7074      1.062          1        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.2it/s 7.4s0.1s
                   all       1066       1595      0.978      0.976      0.987       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      50/50      0.73G      1.588     0.5889       1.24          6        640: 0% ──────────── 1/2134 2.4it/s 0.1s<14:49

c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:401: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sx = feats[0].new_full((w,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift x
c:\Users\Garvit\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\tal.py:402: UserWarning: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\Context.cpp:95.)
  sy = feats[0].new_full((h,), 1, dtype=dtype).cumsum(0) - (1 - grid_cell_offset)  # shift y

      50/50      0.73G      1.462     0.7805      1.058          3        640: 100% ━━━━━━━━━━━━ 2134/2134 16.2it/s 2:120.1ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.1it/s 7.4s0.1s
                   all       1066       1595      0.978      0.974      0.987      0.551

50 epochs completed in 1.959 hours.
Optimizer stripped from D:\Inspectra\experiments\pcb\baseline\baseline\weights\last.pt, 6.3MB
Optimizer stripped from D:\Inspectra\experiments\pcb\baseline\baseline\weights\best.pt, 6.3MB

Validating D:\Inspectra\experiments\pcb\baseline\baseline\weights\best.pt...
Ultralytics 8.4.117  Python-3.11.5 torch-2.5.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 6GB Laptop GPU, 6144MiB)
Model summary (fused): 73 layers, 3,006,818 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 134/134 18.7it/s 7.2s0.1s
                   all       1066       1595      0.977      0.974      0.987      0.549
            mouse_bite        140        280      0.981      0.975       0.99      0.564
                  spur        130        262      0.979      0.966      0.984      0.531
          missing_hole        118        229       0.99      0.996      0.995      0.594
                 short        158        327      0.972      0.957      0.976      0.557
          open_circuit        135        259      0.981      0.974      0.993      0.514
       spurious_copper        121        238      0.962      0.975      0.984      0.537
Speed: 0.3ms preprocess, 3.2ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to D:\Inspectra\experiments\pcb\baseline\baseline

PCB
Training time: 118.77 minutes
Best model: d:\Inspectra\experiments\pcb\baseline\baseline\weights\best.pt

In [9]:
detection_results = {}

for dataset, config in DETECTION_DATASETS.items():

    if dataset in [
        "bottle",
        "pcb",
    ]:
        continue

    if not config["classes"]:
        print(
            f"\n{dataset}: "
            "classes not prepared yet"
        )
        continue

    print(
        f"\n{'=' * 70}"
    )

    print(
        f"BASELINE: {dataset.upper()}"
    )

    print(
        f"{'=' * 70}"
    )

    result = train_detection_baseline(
        dataset,
        config
    )

    detection_results[
        dataset
    ] = result

textile: classes not prepared yet

======================================================================
BASELINE: WELDING
======================================================================
welding: no training images

In [10]:
baseline_summary = []

for dataset in DETECTION_DATASETS:

    result = readiness_df[
        readiness_df["dataset"]
        == dataset
    ]

    if result.empty:
        continue

    row = result.iloc[0]

    baseline_summary.append(
        {
            "dataset": dataset,
            "task": "detection",
            "ready": bool(
                row["ready"]
            ),
            "train_images": int(
                row["train"]
            ),
            "val_images": int(
                row["val"]
            ),
            "test_images": int(
                row["test"]
            ),
        }
    )


baseline_summary_df = pd.DataFrame(
    baseline_summary
)

display(
    baseline_summary_df
)

baseline_summary_df.to_csv(
    EXPERIMENTS_DIR
    / "baseline_readiness.csv",
    index=False
)

   dataset       task  ready  train_images  val_images  test_images
0   bottle  detection   True          5420        1799          920
1      pcb  detection   True          8534        1066         1068
2  textile  detection  False             0           0            0
3  welding  detection  False             0           0            0

In [11]:
import torchvision
from torchvision import datasets
from torchvision import transforms
from torch.utils.data import DataLoader

In [12]:
ROAD_IMAGE_SIZE = 224

road_train_transform = transforms.Compose([
    transforms.Resize(
        (ROAD_IMAGE_SIZE, ROAD_IMAGE_SIZE)
    ),
    transforms.RandomHorizontalFlip(
        p=0.5
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406
        ],
        std=[
            0.229,
            0.224,
            0.225
        ]
    ),
])

road_eval_transform = transforms.Compose([
    transforms.Resize(
        (ROAD_IMAGE_SIZE, ROAD_IMAGE_SIZE)
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406
        ],
        std=[
            0.229,
            0.224,
            0.225
        ]
    ),
])

In [13]:
road_root = (
    PROCESSED_DATA
    / "road"
)

road_train = datasets.ImageFolder(
    road_root / "train",
    transform=road_train_transform
)

road_val = datasets.ImageFolder(
    road_root / "val",
    transform=road_eval_transform
)

road_test = datasets.ImageFolder(
    road_root / "test",
    transform=road_eval_transform
)

print(
    "Classes:",
    road_train.classes
)

print(
    "Train:",
    len(road_train)
)

print(
    "Val:",
    len(road_val)
)

print(
    "Test:",
    len(road_test)
)

Classes: ['Negative', 'Positive']
Train: 28000
Val: 6000
Test: 6000

In [14]:
ROAD_BATCH_SIZE = 64

road_train_loader = DataLoader(
    road_train,
    batch_size=ROAD_BATCH_SIZE,
    shuffle=True,
    num_workers=4,
    pin_memory=torch.cuda.is_available(),
)

road_val_loader = DataLoader(
    road_val,
    batch_size=ROAD_BATCH_SIZE,
    shuffle=False,
    num_workers=4,
    pin_memory=torch.cuda.is_available(),
)

road_test_loader = DataLoader(
    road_test,
    batch_size=ROAD_BATCH_SIZE,
    shuffle=False,
    num_workers=4,
    pin_memory=torch.cuda.is_available(),
)

In [15]:
from torchvision.models import (
    resnet18,
    ResNet18_Weights,
)

road_model = resnet18(
    weights=ResNet18_Weights.DEFAULT
)

road_model.fc = torch.nn.Linear(
    road_model.fc.in_features,
    len(road_train.classes)
)

road_model = road_model.to(
    DEVICE
)

print(
    road_model
)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\Garvit/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:07<00:00, 6.24MB/s]

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=2, bias=True)
)

In [16]:
road_criterion = torch.nn.CrossEntropyLoss()

road_optimizer = torch.optim.AdamW(
    road_model.parameters(),
    lr=1e-4,
    weight_decay=1e-4,
)

In [17]:
def train_classification_epoch(
    model,
    loader,
    criterion,
    optimizer,
    device
):

    model.train()

    total_loss = 0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(
            device
        )

        labels = labels.to(
            device
        )

        optimizer.zero_grad()

        outputs = model(
            images
        )

        loss = criterion(
            outputs,
            labels
        )

        loss.backward()

        optimizer.step()

        total_loss += (
            loss.item()
            * images.size(0)
        )

        predictions = (
            outputs.argmax(
                dim=1
            )
        )

        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

    return (
        total_loss / total,
        correct / total
    )

In [18]:
@torch.no_grad()
def evaluate_classification(
    model,
    loader,
    criterion,
    device
):

    model.eval()

    total_loss = 0
    correct = 0
    total = 0

    for images, labels in loader:

        images = images.to(
            device
        )

        labels = labels.to(
            device
        )

        outputs = model(
            images
        )

        loss = criterion(
            outputs,
            labels
        )

        total_loss += (
            loss.item()
            * images.size(0)
        )

        predictions = (
            outputs.argmax(
                dim=1
            )
        )

        correct += (
            predictions == labels
        ).sum().item()

        total += labels.size(0)

    return (
        total_loss / total,
        correct / total
    )

In [19]:
ROAD_EPOCHS = 10

road_history = []

best_val_accuracy = 0

road_model_dir = (
    MODELS_DIR
    / "road"
)

road_model_dir.mkdir(
    parents=True,
    exist_ok=True
)

for epoch in range(
    ROAD_EPOCHS
):

    train_loss, train_accuracy = (
        train_classification_epoch(
            road_model,
            road_train_loader,
            road_criterion,
            road_optimizer,
            DEVICE
        )
    )

    val_loss, val_accuracy = (
        evaluate_classification(
            road_model,
            road_val_loader,
            road_criterion,
            DEVICE
        )
    )

    road_history.append(
        {
            "epoch": epoch + 1,
            "train_loss": train_loss,
            "train_accuracy": train_accuracy,
            "val_loss": val_loss,
            "val_accuracy": val_accuracy,
        }
    )

    print(
        f"Epoch {epoch + 1:02d}/{ROAD_EPOCHS} "
        f"| "
        f"train_loss={train_loss:.4f} "
        f"| "
        f"train_acc={train_accuracy:.4f} "
        f"| "
        f"val_loss={val_loss:.4f} "
        f"| "
        f"val_acc={val_accuracy:.4f}"
    )

    if val_accuracy > best_val_accuracy:

        best_val_accuracy = (
            val_accuracy
        )

        torch.save(
            road_model.state_dict(),
            road_model_dir
            / "baseline_resnet18.pt"
        )

Epoch 01/10 | train_loss=0.0105 | train_acc=0.9969 | val_loss=0.0024 | val_acc=0.9995
Epoch 02/10 | train_loss=0.0038 | train_acc=0.9988 | val_loss=0.0034 | val_acc=0.9993
Epoch 03/10 | train_loss=0.0017 | train_acc=0.9996 | val_loss=0.0036 | val_acc=0.9993
Epoch 04/10 | train_loss=0.0024 | train_acc=0.9992 | val_loss=0.0042 | val_acc=0.9988
Epoch 05/10 | train_loss=0.0024 | train_acc=0.9993 | val_loss=0.0039 | val_acc=0.9987
Epoch 06/10 | train_loss=0.0021 | train_acc=0.9992 | val_loss=0.0025 | val_acc=0.9995
Epoch 07/10 | train_loss=0.0010 | train_acc=0.9995 | val_loss=0.0027 | val_acc=0.9995
Epoch 08/10 | train_loss=0.0027 | train_acc=0.9992 | val_loss=0.0019 | val_acc=0.9995
Epoch 09/10 | train_loss=0.0007 | train_acc=0.9999 | val_loss=0.0035 | val_acc=0.9990
Epoch 10/10 | train_loss=0.0012 | train_acc=0.9996 | val_loss=0.0026 | val_acc=0.9992

In [20]:
road_history_df = pd.DataFrame(
    road_history
)

plt.figure(
    figsize=(10, 5)
)

plt.plot(
    road_history_df["epoch"],
    road_history_df["train_accuracy"],
    label="Train Accuracy"
)

plt.plot(
    road_history_df["epoch"],
    road_history_df["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel(
    "Epoch"
)

plt.ylabel(
    "Accuracy"
)

plt.title(
    "Road Classification Baseline"
)

plt.legend()

plt.grid(
    alpha=0.3
)

plt.show()